name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    env:
      OS: ${{ matrix.os }}
      PYTHON: ${{ matrix.python-version }}
      PYTHONIOENCODING: utf-8
      PIP_DOWNLOAD_CACHE: ${{ github.workspace }}/../.pip_download_cache
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, macos-latest, windows-latest]
        python-version: [3.6, 3.7, 3.8, 3.9]

    steps:
    - name: Set git crlf/eol
      run: |
        git config --global core.autocrlf false
        git config --global core.eol lf

    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Add pip requirements
      run: |
        python -m pip install --upgrade pip
        pip install tox tox-gh-actions

    - name: Install macos deps with brew
      if: runner.os == 'macOS'
      run: |
        brew install ninja

    - name: Prepare compiler environment for ${{ matrix.os }}
      if: runner.os == 'Windows'
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x64

    - name: Set have package true for ${{ matrix.os }}
      if: runner.os == 'Linux'
      run: |
        echo "HAVE_LIBDATRIE_PKG=TRUE" >> $GITHUB_ENV

    - name: Install deps with apt helper action
      if: runner.os == 'Linux'
      uses: ryankurte/action-apt@v0.2.0
      with:
        # architectures to pass to dpkg --add-architecture
        #architectures: # optional
        packages: libdatrie-dev pybind11-dev ninja-build

    - name: Test in place
      # windows does not like build_ext -i or removing previous build
      if: runner.os != 'Windows'
      run: |
        tox -e py

    - name: Build dist pkgs
      run: |
        tox -e deploy

    - name: Check wheel
      run: |
        tox -e check
