name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    env:
      OS: ${{ matrix.os }}
      PYTHON: ${{ matrix.python-version }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, windows-latest]
        python-version: [3.6, 3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Add python requirements
      run: |
        python -m pip install --upgrade pip
        pip install tox tox-gh-actions

    - name: Prepare compiler environment for Windows
      if: runner.os == 'Windows'
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x64

    # this is supposed to cache automatically
    - name: Install vcpkg plus packages
      uses: lukka/run-vcpkg@v6.0
      if: runner.os == 'Windows'
      with:
        vcpkgArguments: libdatrie:x64-windows pybind11:x64-windows
        vcpkgGitCommitId: 066c6fd712a3b7015388de644e44faf9774f3641

    # This points the extension builder at the vcpkg toolchain file
    - name: Set Windows environment variables
      if: runner.os == 'Windows'
      run: |
        echo "CMAKE_TOOLCHAIN_FILE=$VCPKG_ROOT/scripts/buildsystems/vcpkg.cmake" >> $GITHUB_ENV

    - name: Install deps with apt-get
      if: runner.os == 'Linux'
      run: |
        sudo apt-get -qq update
        sudo apt-get install -y libdatrie-dev pybind11-dev ninja-build

    - name: Test with tox
      run: |
        tox -e py

    - name: Build dist pkgs
      run: |
        tox -e deploy
