name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    env:
      OS: ${{ matrix.os }}
      PYTHON: ${{ matrix.python-version }}
      PIP_DOWNLOAD_CACHE: ${{ github.workspace }}/../.pip_download_cache
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-20.04, windows-latest]
        python-version: [3.6, 3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Add requirements
      run: |
        python -m pip install --upgrade pip
        pip install tox tox-gh-actions

    - name: Prepare compiler environment for Windows
      if: runner.os == 'Windows'
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x64

    # this is supposed to cache automatically
    - name: Install vcpkg plus packages
      uses: lukka/run-vcpkg@v6.0
      if: runner.os == 'Windows'
      with:
        vcpkgTriplet: x64-windows
        vcpkgArguments: libdatrie
        vcpkgGitCommitId: 066c6fd712a3b7015388de644e44faf9774f3641

    # This points the extension builder at the vcpkg toolchain file
    - name: Set Windows environment variables
      if: runner.os == 'Windows'
      run: |
        echo "CMAKE_TOOLCHAIN_FILE=$VCPKG_ROOT/scripts/buildsystems/vcpkg.cmake" >> $GITHUB_ENV

    - name: apt helper action
      if: runner.os == 'Linux'
      uses: ryankurte/action-apt@v0.2.0
      with:
        # architectures to pass to dpkg --add-architecture
        #architectures: # optional
        packages: libdatrie-dev pybind11-dev ninja-build

    - name: Test in place
      if: runner.os == 'Linux'
      run: |
        tox -e py

    - name: Build dist pkgs
      run: |
        tox -e deploy

    - name: Check wheel
      run: |
        tox -e check
